sudo: required
language: node_js
node_js:
  - "10"
cache:
  directories:
  - node_modules
install:
  - npm install -g truffle@5.0.0-beta.1
  - npm install -g ganache-cli@6.1.6
  - npm install
script:
  - npm run test-unit
  - npm run stop
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
